apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: efrei2023/backend:1
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
      imagePullSecrets:
        - name: efrei2023 #kubectl create secret docker-registry efrei2023  --docker-server=docker.io  --docker-username=efrei2023 --docker-password=efrei2023 --docker-email=abdoulzak@proton.me
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: backend
