---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: efrei2023/frontend:1
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: Always
      imagePullSecrets:
        - name: efrei2023
---
#Expose the frontend web server as a Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    name: frontend
spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: http
  selector:
    app: frontend
